version: '3.5'
services:
  client-app:
    restart: alway
    container_name: client
    build:
      context: ./client
      dockerfile: ./client/Dockerfile
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
